export const SET_CURRENT_PLATFORM = 'SET_CURRENT_PLATFORM';
export const SET_PLATFORM_DATA = 'SET_PLATFORM_DATA';
export const SET_PROJECT_LIST = 'SET_PROJECT_LIST';
export const SET_PLATFORMS_LIST = 'SET_PLATFORMS_LIST';
export const SET_CURRENT_PROJECTS_SUBMODULES_PLATFORM = 'SET_CURRENT_PROJECTS_SUBMODULES_PLATFORM';
export const SET_GLOBAL_PLATFORM_DATA = 'SET_GLOBAL_PLATFORM_DATA';
export const SET_PLATFORM_LIBS_DEPENDENCIES = 'SET_PLATFORM_LIBS_DEPENDENCIES';
