version: '3'
services:
  web:
    container_name: versions-tool-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      NODE_ENV: production
      APP_PORT: 3000
      DB_PORT: 27017
      DB_HOST: mongo
      DB_NAMESPACE: versionstool
      DEBUG: "*,-not_this"

  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - /infa-health-status:/data/db
    ports:
      - "27017:27017"